baseURL = 'https://c.harl.ie/'
languageCode = 'en-us'
title = 'C.harl.ie'
copyright = ''
canonifyURLs = true
enableRobotsTXT = true

[params]
name = 'Charlie Hooper-Williams'
role = 'CTO, CPO & Lead iOS Developer'
cv_url = '/CHooperWilliams-tech-CV-2025.pdf'
email = 'c@harl.ie'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
